# Generated by Django 4.2 on 2023-04-19 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_article_posted_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.FileField(
                default="temp.jpg", upload_to="", verbose_name="Путь к картинке"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="posted",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 4, 19, 21, 58, 41, 202672),
                verbose_name="Опубликована",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(2023, 4, 19, 21, 58, 41, 202672),
                verbose_name="Дата",
            ),
        ),
    ]
